### PR TITLE
Issue#898: Fixed connection redirection to Active server for IPv6 addresses

### PR DESCRIPTION
**Pull request by saurabhagas**

### CODE REVIEW

**Comment by saurabhagas** [comment]
test this please

**Comment by saurabhagas** [comment]
test this please

**Comment by myronkscott** [comment]
This doesn't seem to go far enough.  Maybe we should look at making support use the type system rather than parsing strings

**Comment by saurabhagas** [comment]
@myronkscott agreed. I used `TCConnection` to fetch the host and port.

**Comment by saurabhagas** [comment]
Turns out that my current approach doesn't work. Need to investigate more.

**Comment by myronkscott** [comment]
I looked at this.  I think it will take quite a bit to move it to a typed class.  We will have to do with the string parsing for now.

**Comment by saurabhagas** [comment]
Went back to string parsing.

**Comment by saurabhagas** [comment]
@myronkscott, can you please merge and release a version?

**Comment by mathieucarbou** [comment]
Merging - @saurabhagas told eme he got @myronkscott 's approval.

**Pull request merged**
