### PR TITLE
Issue#652: Fixed start-tc-server.sh so that it handles spaces in path

### PR DESCRIPTION
**Pull request by saurabhagas**
1. Made the start-tc-server.sh script adapt to space characters in path.
2. Minor formatting changes.

### CODE REVIEW

**Comment by terracotta-org** [comment]
Can one of the admins verify this patch?

**Comment by saurabhagas** [comment]
@ljacomet, can you please test the script?

**Comment by myronkscott** [comment]
Please remove all the whitespace changes.  It is impossible to tell what is happening in this diff.

**Comment by saurabhagas** [comment]
@myronkscott, done.

**Comment by ramsai1729** [comment]
test this please

**Pull request merged**
