### PR TITLE
change to using byte buffer references for more efficient buffer use

### PR DESCRIPTION
**Pull request by myronkscott**
I'm not sure about the proper reference closing everywhere just yet.  This is a first draft

### CODE REVIEW

**Comment by myronkscott** [comment]
tests pass locally

**Comment by myronkscott** [comment]
tracking down some dangling references.  do not merge yet

**Comment by myronkscott** [comment]
found dangling references fixed.

**Review by chrisdennis — APPROVED** [review]

**Comment by chrisdennis** [comment]
I took a quick look through this and it looks fine, but I assume most of it is iterative on top of the code I've already reviewed. Let me know if there are things you want me to take a closer look at.

**Comment by myronkscott** [comment]
i think we should just go with it. i'll merge and release.

**Pull request merged**
