### PR TITLE
Fix #570: pass synack future when created

### LINKED ISSUE #570: NPE in client when waiting for synack
on handshake, it is possible to hit NPE if synack errors before waiting.

### PR DESCRIPTION
**Pull request by myronkscott**

### CODE REVIEW

**Comment by myronkscott** [comment]
test this please

**Comment by myronkscott** [comment]
test all please

**Comment by myronkscott** [comment]
test this please

**Comment by myronkscott** [comment]
test this please

**Comment by myronkscott** [comment]
test this please

**Comment by akomakom** [comment]
test this please

**Comment by akomakom** [comment]
test this please

**Comment by akomakom** [comment]
test this please

**Comment by akomakom** [comment]
test this please

**Pull request merged**
