### PR TITLE
Improve behavior of PortChooser

### PR DESCRIPTION
**Pull request by cljohnso**
This commit updates PortChooser to:
* Warn when the candidate port pool is less that 1024 ports; a small
  candidate port pool can result in test timeouts.
* Correct logic in isPortUsed resulting in a failure to fully check
  port availability.
* Introduce a connection timeout for the "client connection" test to
  reduce the time taken to test a port.

### CODE REVIEW

**Comment by cljohnso** [comment]
I have an instrumented version of `PortChooser` I used for local profiling.  With the changes in this commit, it went from just over 1s per allocation request (no matter the number of ports because of the testing error) to ~50ms per port -- asking for 8 ports takes ~0.4s.

**Comment by myronkscott** [comment]
With the support module now in tc-platform. I think that leaves this change orphaned.

**Comment by saurabhagas** [comment]
> With the support module now in tc-platform. I think that leaves this change orphaned.

Yes. The `galvan-platform-support` in tc-platform is using the new port chooser.

**Comment by cljohnso** [comment]
> > With the support module now in tc-platform. I think that leaves this change orphaned.
> 
> Yes. The `galvan-platform-support` in tc-platform is using the new port chooser.

The port chooser that was in terracotta-platform has a gap that this one fills.  I'll look at merging the capabilities of both into a version resident in terracotta-utilities.

**Pull request closed without merging**
