### PR TITLE
Reworked TCLogger and TCLogging / Replaces PR #94

### PR DESCRIPTION
**Pull request by mathieucarbou**
This PR replaces PR #94. It includes @anthonydahanne commits, and changes on the TCLogger and TCLogging to support SLF4J and hides Log4J for client runtime. 

Spoken to @lorban and @anthonydahanne : this is a first commit which goal is to make the client-runtime lib __usable__ in client projects. There will still need to completely rework this logging system.

    Updated TCLogging to remove the hard log4j dependencies
    
     - Supports Log4j  by default if it is in the classpath, otherwise uses SLF4J
     - API break: had to remove TCLogger.setLevel() method and some other public methods on TCLogger
     - Provided implementations of TCLogger and TCLogging for both Log4j and SLF4J
     - Removed the JMX Appender (confirmed with @lorban)
     - Client Runtime only contains SLF4J api and ships with externalized log4j and slf4j-log4j
    
- All tests pass
- start-tc-server.sh starts correctly
- I tried Client Runtime in our app, our app can start and client runtime logs can be seen

__IMPORTANT_

This is possible that this PR causes compile issues on other projects relying on TCLogging or TCLogger methods that have been removed. In such case, client code should be updated because we cannot rely on log4j-dependant classes, at least for client-runtime.

### CODE REVIEW

**Comment by mathieucarbou** [comment]
@anthonydahanne, @lorban : this is the PR we talked about.
@ramsai1729 : it replaces PR #94.

**Comment by jd0-sag** [comment]
I am having trouble understanding the scope of the last commit since it includes too many conflated ideas.  Can that be split up into a sequence of commits, so the ideas are isolated?

Also, there is this bizarre removal of the word "public" from many classes, which is extraneous (and sometimes changes the license header).  This part of the change should be reverted.

**Comment by mathieucarbou** [comment]
@jd0-sag : I updated the PR so that is is easier for your team to review.

I firstly renamed classes and made them package local to isolate classes that depends on specific log4j stuff and are only used by the `Log4jTCLogging` class.

I've made this change to be sure that no module will ever use these classes that could cause a client crash in the case a client is not using log4j.

**Comment by ramsai1729** [comment]
I have added few cleanup comments, otherwise this PR seems fine to me. Also, lets not change visibility of the classes.

**Comment by mathieucarbou** [comment]
@ramsai1729 : thanks! I'll update. But please see with @jd0-sag and @myronkscott before merging :-)

**Comment by mathieucarbou** [comment]
Rebased!

**Comment by myronkscott** [comment]
Obsoleted by PR#106

**Pull request closed without merging**
